### ISSUE TITLE
Extra items

### ISSUE THREAD

**Issue by cadz39** [joshhunt/destinySets#100]
Dropped the sparrow from Sloan and the ghost from devrim (not 100% sure though) but both are from planet vendors.

**Comment by joshhunt** [comment]
From   https://twitter.com/cadz39/status/995965564043583489
  

  
Excellent thanks for reporting!
  

  
  

  
  
>

**Comment by cadz39** [comment]
![fcd88cac-d5f2-4ec2-ad09-de930fb2f9b0](https://user-images.githubusercontent.com/39262973/39991283-e9d5b358-5766-11e8-9be2-b71599f5473f.png)
![Uploading 1052F9CB-2DA6-49C0-BA85-6A2A8F4228DB.png…]()

**Comment by cadz39** [comment]
No working on if there’s  specific  Drops from the other 3. But Mercury might take sometime
