### ISSUE TITLE
Suggestion: Separate Bray and Arctic Weapons from normal engram weapons from Ana

### ISSUE THREAD

**Issue by alexcpsec** [joshhunt/destinySets#102]
Bray and Arctic Weapons are (I believe)

- BrayTech Winter Wolf
- BrayTech Osprey
- The Frigid Jackal
- Niflheim Frost
- 18 Kelvins

There is also the "BrayTech RWP Mk. II" which maybe is going to be a proto-Polaris Lance, but that would make 6 weapons where the emblem says it is supposed to be 5 🤔🤔

**Comment by joshhunt** [comment]
Hmm, you're saying that these weapons are not Destination weapons for Hellas Basin:

 * Requiem-45
 * Proelium FR3
 * Hagakure
 * Kibou AR3
 * Telemachus-C

and they're just general engram weapons that can drop from multiple places?

**Comment by alexcpsec** [comment]
No, these ARE destination weapons that drop from the Hellas Basin engrams.

The other ones are not from engrams, they are from the Sleeper nodes quests (as far as I know).

I just think it might be worthwhile to separate them out because they come from different sources, but I would keep both lists under Mars.

**Comment by joshhunt** [comment]
Okay, i split them out into different sections in the same group. Let me know what you think.

**Comment by alexcpsec** [comment]
It looks good to me. However now the rocket launcher could be Strike specific. ¯\_(ツ)_/¯

Maybe I'll wait a bit before making more suggestions

**Comment by alexcpsec** [comment]
Confirmed. The Braytech Osprey is this Nightfall's exclusive item:

https://old.reddit.com/r/DestinyTheGame/comments/8jyqty/confirmed_there_is_an_exclusive_nightfall_reward/dz51njq/?context=1000

**Comment by joshhunt** [comment]
oh amazing. thanks. I saw the reports that it's the exclusive... then people saying it's not... lots of shit going around.
