### ISSUE TITLE
Support for Resonant Frequency tracking?

### ISSUE THREAD

**Issue by Lingnik** [joshhunt/destinySets#111]
Resonant Frequencies show up in the API. Is it possible to get a listing of them under Warmind as a knockout list?

**Comment by joshhunt** [comment]
@lowlines's Maps are a great site for this https://lowlidev.com.au/destiny/maps/mars

I don't think that my site's layout is the best way to present this information. I think I'll let him develop the best experience for trackables at this stage 😃
