### ISSUE TITLE
 Eystein-D pulse rifle not listed in EDZ

### ISSUE THREAD

**Issue by joshhunt** [joshhunt/destinySets#12]
Apparently the  Eystein-D pulse rifle should be in EDZ gear.

https://twitter.com/zavalaluvsme/status/918235733558665216

**Comment by joshhunt** [comment]
Can't find a source claiming this is an EDZ weapon - I think it's from a quest reward actually?

**Comment by Trekoid** [comment]
A few minutes ago, I had the Eystein-D drop from my IO Flashpoint engram, aka Luminous Planetary Engram, as the Additional Reward. The faction reward being a Gensym Guantlet. I took a video clip, if needed. It looks like it is part of the common loot table shared across all NPCs. The planetary engrams say "This engram will contain one faction item, as well as faction shaders and one additional reward." If you sit and watch the planetary engram preview, the items in the Additional Rewards section rotate through multiple items.

**Comment by joshhunt** [comment]
Based on comments and my investigation, Eystein-D isnt actually an EDZ weapon, but is instead one of those random drops that can drop from many vendors.
