### ISSUE TITLE
Sorry man but Bungie just made this entire site obsolete

### ISSUE THREAD

**Issue by TheWolfLegate** [joshhunt/destinySets#121]
Thanks for all the hard work you have put into the site, but Bungie is adding a collections tab. GG

**Comment by joshhunt** [comment]
<img width="354" alt="screen shot 2018-06-05 at 18 16 47" src="https://user-images.githubusercontent.com/46142/40991752-af62e154-68ec-11e8-89cd-9ed0870dd46f.png">
