### ISSUE TITLE
Issue connecting to bungie.net

### ISSUE THREAD

**Issue by pfp-az** [joshhunt/destinySets#13]
Last night I received at least 3 items i didn't previously have.  When I checked destinysets they still showed as missing.  I tried refresh but no help. Tried deleting cookies and added my xbox account again but now everything shows as unfound.  Tried a different browser and also everything unfound.

**Comment by pfp-az** [comment]
No sooner do I post this that it starts working again.

**Comment by joshhunt** [comment]
oh good, then my fix worked :)
