### ISSUE TITLE
Eververse Exotic Ornaments on "All Seasons" Page

### ISSUE THREAD

**Issue by yungando** [joshhunt/destinySets#149]
Hi, I was wondering if the exotic weapon and armour ornaments could also be view-able on the "All Seasons" page, separated by season. The rest of the Eververse items are already there and it's a shame to have to flick between this page and the "All Items" page just to see the Ornaments.

Sorry if this has already been addressed.

Cheers

**Comment by joshhunt** [comment]
Sounds like an oversight on my part. Ill try and get this done in the next day or so, but it might be rough with all the Forsaken stuff happening 😂   
  

  
  

  
  
>

**Comment by yungando** [comment]
As I said before, they are visible on the "All Items" page, but they aren't under the "Forsaken" and "Year 1" tabs with the rest of the Eververse Items.

![image](https://user-images.githubusercontent.com/9106643/45115324-6d56ce80-b147-11e8-8a8a-f8f1580d02db.png)

Everything else is there except all of the Exotic and legendary ornaments. This has been the same for all the year 1 ornaments. It would be nice if the Year 1 Exotic weapon and armour ornaments were also displayed under Eververse like everything else is, separated by season.

![image](https://user-images.githubusercontent.com/9106643/45115441-bb6bd200-b147-11e8-8d2f-b9ae64603315.png)

**Comment by Jakosaur** [comment]
I've added the Year 1 Eververse Ornaments in on my branch for Year 1 to make the Eververse sets consistent. Will push them with Crimson Days 👍
