### ISSUE TITLE
Eververse Bundle Exclusive Items

### ISSUE THREAD

**Issue by Jakosaur** [joshhunt/destinySets#174]
Was thinking about this last week & again today after seeing another new Eververse bundle, whether to separate them into a different section if the items inside are exclusive to a bundle. A bit like this so it shows when the bundle is on-sale for those who want to buy them. Want to hear your opinion on this 🙂

![image](https://user-images.githubusercontent.com/20144356/47098461-2cb0a180-d22b-11e8-9efc-1d9f06827a99.png)

Would only involve moving them to the bottom of the Eververse/FotL sections to make it more clear they're exclusive items! Could even just have the items separated without the bundle icons. 🙂

**Comment by joshhunt** [comment]
What's your thoughts on just remove the bundle exclusive items from the curated collections page? They'll be in All Items for those that collect them, and then they'll be out of the road for everyone else.

**Comment by Jakosaur** [comment]
Yeah that's another option. That's probably the best option unless there's a way for people to filter them in (off by default) on the curated collection pages.
