### ISSUE TITLE
Item perks page fails to render when user has no instances of the item

### ISSUE THREAD

**Issue by tomcorke** [joshhunt/destinySets#175]
I can view pages for items when I am logged in and where I own one or more of the item, e.g. Whisper of the Worm shows me the perks of the instance of the gun that I have in my inventory

I cannot view a page for an item that I do not own an instance of, or any item when I am not logged in.

Example: Whisper of the Worm perks page: https://destinysets.com/item/1891561814

Works while logged in and having one, does not work while logged out.

**Comment by tomcorke** [comment]
The error in console is 
```
raven.js:58 TypeError: Cannot read property 'map' of undefined
at u (index.js:185)
```

```
184:          <h2>Instances</h2>
185:          {instances.map((instance, index) => (```
186            <div key={index}>
```

**Comment by Daynar100** [comment]
I have a solution to this, although it is basically just sidestepping the issue. 
[Here is a branch with the 'fix'.](https://github.com/Daynar100/destinySets/tree/ItemPage-Crash-Fix)
The code just gives instances a dummy value when it is undefined. 
`
    if (typeof instances === 'undefined')
      instances = {map: function(trash){}}
`
