### ISSUE TITLE
Your OAuth may be comprimised!

### ISSUE THREAD

**Issue by Sven2157** [joshhunt/destinySets#185]
I have had an account with Blizzard since the beginning.  However, until I authorized your app, 4 days ago, to access my Blizzard account, I have been hacked twice.  I have BOTH Blizzard Authenticator and SMS turned on.  They seem to bypass that - each time.

Authorizing your site to access my information is the ONLY thing I have done, in the last 10 years.  This may be a bug on Blizzard's end.  But I am just informing you, as stated above.

**Comment by joshhunt** [comment]
Hey @Sven2157, thanks for the message, and I'm sorry to hear your Blizzard account is being compromised.

I just wanted to clarify a few points here though that might help you out:

 - DestinySets.com doesn't actually store any oAuth credentials on any server. DestinySets.com is entirely browser based with no server components. Credentials are stored locally in your browser in localStorage (like a cookie), and communicate with Bungie directly. 

 - As @lowlines points point, Bungie oAuth does not grant access to your Blizzard account, and the tokens supplied are not able to be used with any part of you Blizzard account. The tokens give access to very limited information for your Bungie Destiny account (like reading your inventory). They cannot be used to log in as you, or be used to access the game.

When you log into DestinySets.com, you do so with your Bungie account, not your Blizzard account. Although it just so happens that you log into your Bungie account with your Blizzard account, As a consumer of the _Bungie_ API, DestinySets.com never receives any of this information or authentication. There is no direct relationship between your Blizzard account and third party Destiny apps, like DestinySets.com

If you haven't already, I would recommend getting in touch with Blizzard about your account, and see how they can help you out. 

Cheers,
Josh.
