### ISSUE TITLE
missing sets

### ISSUE THREAD

**Issue by strikeknight57** [joshhunt/destinySets#20]
this is just one set that is missing, but the icarus drifter set for the hunter is missing from the sets that can be found. anyone know of any others?

**Comment by Trekoid** [comment]
Icarus Drifter is under Other - Hunter Specific Sets
![screen shot 2017-10-27 at 12 31 51 pm](https://user-images.githubusercontent.com/2205894/32121791-ea478938-bb12-11e7-8e27-0db4f2389c57.png)

**Comment by strikeknight57** [comment]
That's weird... why isn't it showing up one what I'm looking at? here is a screen cap:
![2017-10-27](https://user-images.githubusercontent.com/33139605/32123931-51ed7be6-bb23-11e7-8912-cf67600700f6.png)

**Comment by Trekoid** [comment]
Is your Bungie.net account associated with Xbox or PS4? I see an Xbox icon in your Windows toolbar.
It is PS4 exclusive, so maybe DestinySets filters it out, because you cannot acquire it?

**Comment by strikeknight57** [comment]
I didn not realize it was ps4 exclusive.... I guess that makes it so that I
can't get it....  May want to put a note on all ps4 exclusive items that
they are so.

On Fri, Oct 27, 2017 at 2:44 PM, Michael Rasmussen <notifications@github.com

**Comment by pfp-az** [comment]
Click the filters dropdown.  There is an option to show / hide PS4 exclusives.

**Comment by joshhunt** [comment]
No missing items, just foreign console exclusives are filtered out by default.

Maybe that could be more obvious.
