### ISSUE TITLE
Legend of Acrius twice in the exotic in the "all" tab

### ISSUE THREAD

**Issue by CyberClaw** [joshhunt/destinySets#21]
Collectors probably care about getting the final version, and don't care about the first version without perks. I think both these entries should be converged into one.

**Comment by Trekoid** [comment]
Agreed. It confused me at first, because the icons look the same, and I was sure I had the weapon. Maybe never display the one that is not upgraded?

**Comment by joshhunt** [comment]
This should be resolved now
