### ISSUE TITLE
Nightfall emblem tracking

### ISSUE THREAD

**Issue by PuLSAz0r** [joshhunt/destinySets#217]
Hello,
The nightfall emblem variants I have aren’t showing as ticked off - not sure if it’s something wrong on my end or a tracking issue? 

Amazing site. Thank you for your hard work

PS- They do seem to tick off once I’ve equipped the emblem and refreshed the page, but never without equipping.

**Comment by Jakosaur** [comment]
This is an issue on Bungie's end unfortunately. Only way Destiny Sets can currently see the variants is when you have the emblem in your inventory, as you have mentioned. Someone has already suggested for Emblem Variants to be available in the collections API, so hopefully one day it's available 👍 

https://github.com/Bungie-net/api/issues/840#issuecomment-451193924

**Comment by PuLSAz0r** [comment]
Ah that makes sense. Thanks for getting back to me - your site is awesome

Sent from my iPhone

On 9 May 2019, at 16:48, Jakosaur <notifications@github.com<mailto:notifications@github.com>> wrote:


This is an issue on Bungie's end unfortunately. Only way Destiny Sets can currently see the variants is when you have the emblem in your inventory, as you have mentioned. Someone has already suggested for Emblem Variants to be available in the collections API, so hopefully one day it's available 👍

Bungie-net/api#840 (comment)<https://github.com/Bungie-net/api/issues/840#issuecomment-451193924>

**Comment by Jakosaur** [comment]
Yeah, @joshhunt's site is amazing! He's done a lot of work to get it to where it is today 🙂
