### ISSUE TITLE
Include location obtained info

### ISSUE THREAD

**Issue by strikeknight57** [joshhunt/destinySets#22]
One recommendation that I would give is to add where each item can be obtained. possibly even put recommended areas to look for each item. for example the Icarus Drifter set is best farmed on IO. Why that is I have no idea but that is what a community that I am a part of came to that conclusion.

**Comment by joshhunt** [comment]
I think, more or less, this is tackled already by the site.

I'm very hesitant to get into business of reporting on hard-to-verify information, and this seems some to be down that alley.
