### ISSUE TITLE
[bug] solstice armor set progress

### ISSUE THREAD

**Issue by hollowhalls** [joshhunt/destinySets#230]
armor progress on my warlocks blue set does not show up as completed, though i have the full purple set and have steps done towards masterwork.
![image](https://user-images.githubusercontent.com/15838634/62436186-8031a480-b704-11e9-81f0-a9885183823b.png)

**Comment by joshhunt** [comment]
thanks for the report, I'll look into it!

**Comment by tomcorke** [comment]
I'm seeing the same for my Hunter, although my Titan shows correctly

**Comment by joshhunt** [comment]
Have you unlocked the purple Majestic set on your Titan?

**Comment by tomcorke** [comment]
Yes, majestic sets unlocked on both Hunter and Titan:
![image](https://user-images.githubusercontent.com/2150548/62773346-db172300-ba99-11e9-8203-859285767630.png)

**Comment by joshhunt** [comment]
thanks for all the details.

this should be fixed now by https://github.com/joshhunt/destinySets/commit/14216b67b67d9f547536e444bdcc492543ee9341
