### ISSUE TITLE
Some of the weapons are not tracked correctly

### ISSUE THREAD

**Issue by michaelnemtsev** [joshhunt/destinySets#231]
Hi, I've noticed that some of the weapons aren't recognised as owned. For example, I have Redrix but it appears as I don't have it
![image](https://user-images.githubusercontent.com/32570088/62818214-c6b15400-bb87-11e9-985c-87159e647718.png)

**Comment by Jakosaur** [comment]
I think that’s the Claymore as it has the Warmind logo. When looking at your profile, I can only see Broadsword (Forsaken Logo). Do you have the Redrix’s Claymore? Thanks

On 10 Aug 2019, at 06:59, Michael Nemtsev <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I've noticed that some of the weapons aren't recognised as owned. For example, I have Redrix but it appears as I don't have it
[image]<https://user-images.githubusercontent.com/32570088/62818214-c6b15400-bb87-11e9-985c-87159e647718.png>

**Comment by michaelnemtsev** [comment]
You are right I only have the Broadsword. The logo is identical, my fault. Let's close this issue then
