### ISSUE TITLE
Issues with some exotics

### ISSUE THREAD

**Issue by IronCrystal** [joshhunt/destinySets#244]
There appears to be a few issues with the exotics tracking on the all items page.

https://destinysets.com/all-items

This is not comprehensive in any way but a few issues I found.

https://i.imgur.com/VEoe4Uw.png

I see the Astrocyte Verse helmet in here twice, one faded and one not faded.

I also see several armors such as the Geomag Stabilizers and Chromatic Fire chestplate that are not faded, but I do own them (my geomag is equiped atm and chromatic fire is in vault).

I am assuming that faded means I own it, and non-faded means it's not owned, but if this is not the case then I couldn't figure out what it means.

**Comment by delphiactual** [comment]
Armor 2.0 vs Armor 1.0

**Comment by IronCrystal** [comment]
@delphiactual How do I know which armor is 2.0 vs 1.0?
