### ISSUE TITLE
Support for Simplified Chinese Language

### ISSUE THREAD

**Issue by xyx0826** [joshhunt/destinySets#256]
Currently the Chinese language is defined as:
https://github.com/joshhunt/destinySets/blob/5389f6496aff626214d3d3845bc5a25d633526bc/src/lib/i18n.js#L54-L57
Which is, in fact, Traditional Chinese. Destiny 2 have now added support for Simplified Chinese `zh-chs`. It would be great if an option for `zh-chs` can be implemented in DestinySets and DestinyDataExplorer.

**Comment by xyx0826** [comment]
I'm trying to create a PR but I'm having trouble testing it out since the app constantly crashes on my Windows machine with `req.handle.writev is not a function`.

**Comment by xyx0826** [comment]
#257 should do it. Activity names and descriptions are only partially localized but it looks like a problem of Bungie's data source.

**Comment by xyx0826** [comment]
Thanks.

For data explorer: `zh-chs` is missing from Bungie's `/Platform/Settings/` endpoint probably because their webpage isn't localized in Simplified Chinese (but the game is.) Would be great if the language can be patched in after fetching platform settings.

Simplest would be adding an option to the language dropdown - and it works well:
`<option value="zh-chs">简体中文</option>`

**Comment by delphiactual** [comment]
Data explorer is in a different repo

https://github.com/joshhunt/destinyDataExplorer

**Comment by xyx0826** [comment]
Ahh my bad, I was wondering why I couldn't find its code. Thanks.

**Comment by joshhunt** [comment]
Cheers - I’ll take a look at this!

**Comment by xyx0826** [comment]
Much appreciated. I don't have much experience with Node/React and I'm having trouble setting up my VSCode debugger. Still I'll see what I can do.

**Comment by xyx0826** [comment]
Update: I've created a PR over at the data explorer repo (https://github.com/joshhunt/destinyDataExplorer/pull/13). Thanks for taking a look.
