### ISSUE TITLE
Savior of the Past is erroneously listed as crucible

### ISSUE THREAD

**Issue by delphiactual** [joshhunt/destinySets#263]
https://data.destinysets.com/i/InventoryItem:1736897079

This has a redacted source, which is most likely sundial; not crucible

**Comment by Jakosaur** [comment]
I'll get it moved in the next PR. Saw it with a redacted source, but was related to Shaxx - https://www.light.gg/db/vendors/3603221665/lord-shaxx/ 🙂

**Comment by delphiactual** [comment]
Yes, but I am not sure how light.gg assumes that.

**Comment by Jakosaur** [comment]
It's in his `Categories` https://data.destinysets.com/i/Vendor:3603221665

I'll move it or hide it until the source is confirmed in the next PR.
