### ISSUE TITLE
Display item count and percentage collected

### ISSUE THREAD

**Issue by soundcheck2007** [joshhunt/destinySets#28]
Would there be a way we could add the counts for each set and overall gear to each section.
For example:
At the top it would say (77/500) total collected"
Then in the Iron Banner section, next to weapons is say (10/15)
and the same for the armor.

I think this would be a pretty helpful addition.

**Comment by joshhunt** [comment]
Yes! I agree this is required!

One small question though - what do you think the total number should be? I'm thinking it makes most sense to display how many items _after_ filters are applied. That way the total might change (if you turn titan gear on or off), but at least it'll most useful to Xbox users and those who don't have all classes.

**Comment by soundcheck2007** [comment]
I know this doesn't answer your question exactly but maybe something like this could work too?
<img width="1276" alt="screen shot 2017-11-08 at 4 17 34 pm" src="https://user-images.githubusercontent.com/4165638/32577706-740ede6e-c4a0-11e7-9e05-289d11f94702.png">

**Comment by soundcheck2007** [comment]
I forgot to mention that it would be nice to have a filter to show the weapons too.

**Comment by joshhunt** [comment]
Shipped an initial version of this tonight! Shows percentage by default, but clicking it toggles it to show counts.

**Comment by soundcheck2007** [comment]
Awesome Job!  I don't know what the desired effect is but when "Collected" isn't checked it shows 0/X or 0%.  I thought it was a bug at first and that it was always showing 0%.  Just and FYI for future releases.

**Comment by joshhunt** [comment]
Yes...  it's showing how many items have been collected after filtering is applied. If you unset the 'Collected' filter, there will be no more collected items post-filter, thus everything will be 0%.

I'll look into somehow ignoring the 'collected' filter when doing calculating these stats...
