### ISSUE TITLE
Blank squares without information and no arrivals mods in mods section 

### ISSUE THREAD

**Issue by quetschke** [joshhunt/destinySets#297]
As the title says, blank mods and no season of arrivals mods. See picture below.

Also please note the strange "Ammo Reserves" entry between Dawn and Worthy in the void row.

![image](https://user-images.githubusercontent.com/5354403/84585123-f34e8180-add1-11ea-8809-fdbc260a0fb6.png)

**Comment by Jakosaur** [comment]
Hopefully this'll look better! Will have to investigate the Arrivals mods showing as collected, when they're not. Maybe they aren't in collections? Will need to look further though.

![image](https://user-images.githubusercontent.com/20144356/84603720-6d414200-ae88-11ea-909d-59dea9c64691.png)

**Comment by delphiactual** [comment]
they are not in collections

**Comment by quetschke** [comment]
Looks good! Any ETA for the arrival of the patch to destinysets.com/mods ?

**Comment by joshhunt** [comment]
I'm not going to lie - im not really spending much time developing destiny
sets these days.

I'll generate new mods data for the page and see what happens.
