### ISSUE TITLE
NPM/Yarn installation instructions should mention fontawesome

### ISSUE THREAD

**Issue by cbiesinger** [joshhunt/destinySets#302]
Hi there!

I just tried to run a local instance of destinysets. I ran into this error:
```
$ yarn install
yarn install v1.22.4
error An unexpected error occurred: "Failed to replace env in config: ${FONTAWES
OME_NPM_AUTH_TOKEN}".
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\cygwin64\\home\\Christian\\destinySets\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.
```

Per https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers, I conclude that destinysets seems to require a fontawesome pro subscription. If that's right, it would be good to mention that in the readme. Thanks!

**Comment by joshhunt** [comment]
The code now uses font awesome from the CDN, so this has resolve itself!
