### ISSUE TITLE
[Suggestion] Show full set when hovering over name

### ISSUE THREAD

**Issue by mikevb1** [joshhunt/destinySets#32]
Easier viewing the whole set together as opposed to mentally piecing it together.
Rough mockup ![image](https://user-images.githubusercontent.com/8661717/32645022-028eb516-c59a-11e7-9cfa-bff7e0c94ce8.png)

**Comment by AlexeyDemedetskiy** [comment]
👍 Do you know API that can return the whole image?

**Comment by joshhunt** [comment]
Yeah, this is something that I really want to do, but actually in a seperate 'set details' page where you could see more stats about the gear and set.

Unfortunately these images aren't available in the API so it would need to be another piece of manual curation which I'm hesitant to do.

**Comment by joshhunt** [comment]
Closing for now until there's a good way to get full imagery.
