### ISSUE TITLE
A suggestion about server costs

### ISSUE THREAD

**Issue by KalilaViolette** [joshhunt/destinySets#33]
Since you're asking people how to handle server costs, I use a site for a different game (Final Fantasy XIV) that asks users for support to maintain server costs since they don't even play the game anymore but update it for the community.

http://ffxiv.ariyala.com/

something simple like that could work, also nothing wrong with Patreon either.

**Comment by joshhunt** [comment]
Actually, there's PayPal now. It doesn't fully cover server costs, but it's good enough.
