### ISSUE TITLE
Having trouble logging out

### ISSUE THREAD

**Issue by SavedByGrace-777** [joshhunt/destinySets#38]
First of all, let me just say thank you very much for the great app!

Ok, on to the problem, I am logged into my Destiny 2 PC account on Destiny Sets and am unable to log out in order to get to my PS4 account on DS.  Thank you in advance for the help.

**Comment by SavedByGrace-777** [comment]
I should also say that I've tried my different logins on Bungie, restarted my computer, tried on another computer, and still not figuring out how to log out.

**Comment by joshhunt** [comment]
Hey, are both the PC and PS4 accounts linked to the same Bungie account? (confusing, I know)

Once logged in (via one platform, it doesn't really matter which) you can switch platforms by clicking your gamertag in the top right - there should be a selector there to let you switch platforms.

If not, are you able to switch platforms using DIM fine? What are your gamertags/usernames for all platforms?

<img width="216" alt="screen shot 2017-12-04 at 10 32 33 am" src="https://user-images.githubusercontent.com/46142/33548241-7df635a6-d8de-11e7-911b-a1ca6e845a4c.png">

**Comment by SavedByGrace-777** [comment]
I think I had tried all combinations last night.  However, I just checked and I now have both my logins showing when I click the dropdown menu.  On PS4 I am SavedByGrace_777, and my Btag is SavedByGrace#11149.  Thank you for the comment.
