### ISSUE TITLE
Misleading Information for new players. 

### ISSUE THREAD

**Issue by BijeeOCD** [joshhunt/destinySets#386]
In the holiday and special events section under the Bungie 30th Anniversary Event tab it states the seasonal items are "earnable" during the event. This can be misleading to new players looking to your site to gain some knowledge when in game they arent earnable you have to purchase silver to buy them in the eververse. 

![Screenshot 2021-12-25 1 06 24 PM](https://user-images.githubusercontent.com/93737843/147392041-d7ddaa05-8faa-48fb-aa04-6e11de3ba416.png)

**Comment by JayJTD** [comment]
Guardian Games has the same issue, I think separating events into "Earned" and "Purchased" would cause more confusion than how they're laid out currently.

However, adding a filter to hide all items with "Source: Eververse" would be an amazing feature as it'll allow people to easily know whether or not they've collected all items earned through gameplay.

**Comment by Jakosaur** [comment]
Hi 👋

All Eververse items shown on Destiny Sets have or are going to be sold for Bright Dust, to make sure players can only see items they can acquire with an in-game earnable currency in the current week or hopefully in the future. Any items that have or are only going to be sold with Silver are hidden from view.

Regarding the event descriptions, I'll look at rewording them!

I've worked on an 'Eververse items' filter, hiding any items with a collection source of 'Eververse' or 'Bright Engram'. The only problem is that Destiny 2 doesn't have all items in the collections system, so Ghost Projections, Emotes and Exotic Armour Ornaments wouldn't be hidden. There might be even more items that won't disappear, like glows and antlers but I'm unsure about those. Just not sure if having a filter that doesn't work for all Eververse items is the right call currently, without having to manually update a blacklist every season or content drop. I agree having a filter for Eververse items in any section would be a fantastic way to only see earnable loot! 🙂
