### ISSUE TITLE
Season 2?

### ISSUE THREAD

**Issue by mschemerii** [joshhunt/destinySets#39]
VERY NICE JOB on this!!

What are your plans to reflect any season 2 armor/weapon changes?

**Comment by TrueHeresy** [comment]
Also hoping for season 2, anything that can be done to help you with it?

**Comment by joshhunt** [comment]
Hey @TrueHeresy what Season 2 content are you looking for?

I've got a select few sets up on the homepage (Mercury and Eververse Season 2), and all DLC1 gear is on the All Tabs page.

If there are any specific sets you think the site could do with, it could be helpful to create them yourself and send it through an issue here.

 1. On desktop, go to the 'Data Explorer' tab.
 2. Click the "Explore the entire Destiny 2 database." heading once. The text should change to "_Collect mode is on_"
 3. Add items by searching for it and clicking it. It should appear in the sidebar
 4. As you add each item, the code for the set is copied to your clipboard. Paste it here and I'll check it out :)

**Comment by TrueHeresy** [comment]
No problem, I'll give that a go - the basics are adding the the season 2 weapons of the respective vendors.
I wonder if ornaments are tougher as they don't seem to track accurately, seems like they are in inventory until they're equipped so maybe they can't be read by the API?

**Comment by TrueHeresy** [comment]
Crucible stuff
==========
Basically the same but includes the new faction weapons (there may be more?) and the new faction armour ornaments. I think all the city vendors are like this so I will try to add the new stuff in between uni stuff!
***

[
  {
    "title": "Weapons",
    "items": [
      3336215727, // Martyr's Make
      4193877020, // Does Not Compute
      1048266744, // Better Devils
      1325579289, // Retrofuturist
      4174481098, // Steel Sybil Z-14
      2660862359, // Gentleman Vagabond
      1773600468, // Critical Sass
      2621637518, // Play of the Game
      1674742470, // Autumn Wind
      2792181427, // Tiebreaker
      1084788061, // Swift Solstice
      468276817 // Nature of the Beast
    ]
  },
  {
    "title": "Hunter armor",
    "items": [
      3223280471, // Swordflight 4.1
      2296691422, // Swordflight 4.1
      2718495762, // Swordflight 4.1
      3140634552, // Swordflight 4.1
      3313736739 // Binary Phoenix Cloak
    ]
  },
  {
    "title": "Titan armor",
    "items": [
      2191401041, // Phoenix Strife Type 0
      849529384, // Phoenix Strife Type 0
      2815422368, // Phoenix Strife Type 0
      1484937602, // Phoenix Strife Type 0
      1742680797 // Binary Phoenix Mark
    ]
  },
  {
    "title": "Warlock armor",
    "items": [
      1764274932, // Ankaa Seeker IV
      636679949, // Ankaa Seeker IV
      1333087155, // Ankaa Seeker IV
      1307478991, // Ankaa Seeker IV
      3538513130 // Binary Phoenix Bond
    ]
  },
  {
    "title": "Other",
    "items": [
      2806246104, // Soaring Sword Ornament
      3460422045, // Soaring Sword Ornament
      2646135315, // Soaring Sword Ornament
      337811599, // Soaring Sword Ornament
      1181382726, // Soaring Sword Ornament
      2516513295, // Ankaa Friend Ornament
      121382562, // Ankaa Friend Ornament
      2521913126, // Ankaa Friend Ornament
      3980640404, // Ankaa Friend Ornament
      36130859, // Ankaa Friend Ornament
      2908316342, // Phoenix Battle Ornament
      3955222467, // Phoenix Battle Ornament
      3440657549, // Phoenix Battle Ornament
      2685752725, // Phoenix Battle Ornament
      1617637028 // Phoenix Battle Ornament
    ]
  }
]

**Comment by alexcpsec** [comment]
Hey, folks! I think #40 should do the trick. No ornaments though

**Comment by TrueHeresy** [comment]
Awesome, any particular reason for no ornaments as they do appear at the vendor screen whenever you visit them? 
I can add those if you'd like?

**Comment by alexcpsec** [comment]
@TrueHeresy nah, just lazy. :) I'm going to update it with that.

To be fair, when we look at the ornaments on "All Items", it doesn't seem to be able to tell if you have it unlocked or not. I think there is some additional API checking code we need, and that is definitely a @joshhunt question

**Comment by joshhunt** [comment]
Correct. Ornaments do show up on the All Items page (for English only until https://github.com/Bungie-net/api/issues/319#issuecomment-350134561 lands), but it doesn't take into account ornaments that are applied to items. Shaders will also suffer from this, but its generally not noticeable as usually you have many of them. Works needs to be done to improve this.

**Comment by alexcpsec** [comment]
It being applied or not is not so much the issue, but it if is unlocked or not on the account.

**Comment by joshhunt** [comment]
Okay, so I did some investigation into Ornaments.

the ***tl;dr*** is that there's no API for directly seeing what Ornaments have been unlocked for an account, but I can instead see what Ornaments have been unlocked for *items in the player's inventory or vault*.

So it's a start (and this has been deployed now), but it does mean the site isnt going to be able to see Ornaments for dismantled items.

**Comment by alexcpsec** [comment]
I can see it on the website. Looks like a good compromise to me!

Might be worth opening a ticket with Bungie as a feature request (if you haven't already) 

Thanks again!
