### ISSUE TITLE
Feature: All Seasons Tab

### ISSUE THREAD

**Issue by lowlines** [joshhunt/destinySets#44]
A tab filter that displays both "Base" and "Curse of Osiris" (and future DLCs) using the grouped layout of those tabs. The DLC icons on the item icons already identify what DLC they are from. DLC filters will probably need to be put into a dropdown as there is already "Curse of Osiris" and "The Dawning".

**Comment by joshhunt** [comment]
Very high on the priority list.

Thinking of a way to do this... Perhaps each set (and section within each set?) could have an ID, and then on a new "All Sets" tab all the sets across the different setData files are merged together, by the IDs

**Comment by joshhunt** [comment]
Okay so I'm finally doing this! I'm really unsure about how the whole information hierarchy will work across the whole site, but this at least is my first stab for it on a set level:

![localhost_4000_ 1](https://user-images.githubusercontent.com/46142/39068704-7b159136-44dd-11e8-8e50-e9d7ff088bb6.png)
![localhost_4000_ 2](https://user-images.githubusercontent.com/46142/39068706-7d607730-44dd-11e8-9719-857cf85b0b96.png)

Anyone have any particular thoughts for this? Should this be the _only_ place that Iron Banner gear appears (remove ornaments from the CoO page)?

**Comment by joshhunt** [comment]
oh I did this!
