### ISSUE TITLE
Some weapons are missing to faction weapon list.

### ISSUE THREAD

**Issue by bdh0404** [joshhunt/destinySets#55]
Eystein-D: EDZ
First In, Last Out: Arcology
The Mornin' Comes: Nessus
Death Adder: Io
is included in each faction engram table, but not included in the site.

You can check each list on Data Explorer with EDZ engram, Arcology engram, Nessus engram, IO engram

**Comment by joshhunt** [comment]
Hmmm... I'm not exactly sure about these (Eystein-D has been haunting me for a while), especially because the 'Engram' data in the manifests are very unreliable for the purpose needed for this site.

I've added them in, and I'll monitor the situation.

**Comment by bdh0404** [comment]
Devrim was selling eystein-D and asher did death adder 2 days ago. So I opened this issue.
