### ISSUE TITLE
Exotic Ornaments not recording properly in Google Drive.

### ISSUE THREAD

**Issue by peabeu** [joshhunt/destinySets#56]
I have pretty well all the exotics and their ornaments. The ornament section is only recording a small amount of the ornaments I have currently equipped and or deleted. If I purchase a deleted exotic from the vault/kiosk I can equip the ornament, refresh Destiny Sets and it then shows I have it. If I delete that exotic and refresh, there is no record in DS. As the sample in the image shows, it is working (recording in Google Drive) for some but not others.
![exorn](https://user-images.githubusercontent.com/34254703/36350783-055cc48e-14f2-11e8-828f-8612cc5816fe.jpg)

To name a few, I have the ornaments for Sunshot, Fighting Lion and Cold Heart but not showing as Dismantled like the Vulcans Heart ornament

**Comment by joshhunt** [comment]
Actually, if you're getting grey ticks for 'dismantled' (exotic) ornaments, that's a bug.

Ornament tracking in unreliable enough that I decided to disable the grey ticks for them, even though I am still recording the data to Google Drive all the same. I'll look at chasing down why the grey ticks still show up some time, as well as seeing if there's a way I can make this deficiency more obvious.
