### ISSUE TITLE
Show tracked stats on emblems

### ISSUE THREAD

**Issue by billy-7** [joshhunt/destinySets#63]
Show tracked stats on emblems in the item tooltip

Example
![image](https://user-images.githubusercontent.com/14146945/36640539-a1efb174-1a6c-11e8-8e70-88552a01bb9a.png)

**Comment by joshhunt** [comment]
This actually shouldn't be all that hard to do. Tracked stats on emblems are exactly the same, data wise, as the objectives on Ornaments.

It won't come immediately, but I like this!

**Comment by billy-7** [comment]
Yeah im working on it might have a PR soon

**Comment by joshhunt** [comment]
Cool - let me know how you go.

I know that `processSets` code is a big mess. Ultimately, I think you'll want to make some changes to `objectivesForItem` get it to include the objective data on Emblems.

Let me know how you go or if you have any questions!

**Comment by billy-7** [comment]
I have the tracking working but some of the descriptions are quite long. I think cutting off the descriptions is the best way to do it what do you think @joshhunt 

![image](https://user-images.githubusercontent.com/14146945/36644385-50a77dd6-1aa5-11e8-83b2-5018a4a841c5.png)

**Comment by joshhunt** [comment]
I'll close this in favour of the PR :)
