### ISSUE TITLE
Ghosts

### ISSUE THREAD

**Issue by RlxdN10sity** [joshhunt/destinySets#68]
Ghosts are no longer showing up for me on destinysets.com
There used to be a section showing all the ghosts. For the last several days that section no longer appears for me. Not sure if it's something to do with my browser. I thought someone would've already posted the issue by now or it would just start working again, but neither has happened so figured I'd post. I'm using Firefox browser. Everything else on the site shows up as it always did. Thank you for all your work!

**Comment by joshhunt** [comment]
fixed this.

**Comment by joshhunt** [comment]
thanks for reporting and finally prompting me to get on it!
