### ISSUE TITLE
Bug: Ornaments & Language

### ISSUE THREAD

**Issue by benzolchildhood** [joshhunt/destinySets#74]
Maybe not real bug, but
When langueages Spanish, Spanish (Latin America), Russian, Polish, Chinese picked "Ornaments" section of All Data tab just disapear imideatly.

**Comment by joshhunt** [comment]
Yikes! Real bug. I know what's going on here.

Thanks for letting me know.

**Comment by joshhunt** [comment]
I fixed this a while ago actually!
