### ISSUE TITLE
Titan Alternate emblems not showing acquired

### ISSUE THREAD

**Issue by andyschaefer** [joshhunt/destinySets#75]
I have all 4 titan emblem variants, but none of them are showing up as being acquired.   The other planets do look like they line up correctly.

**Comment by andyschaefer** [comment]
Also, the crucible (warlocks killed, hunters killed, etc) all are not reporting as being acquired either

**Comment by joshhunt** [comment]
Emblem variations aren’t tracked yet. Good news though - I know how to track them and I’m working on a revamp and they’ll be included.   https://twitter.com/joshhunt/status/975494277995384834
  

  
  

  
  
>

**Comment by andyschaefer** [comment]
Interesting.  The weird thing is that the IO, Nessus and EDZ emblem variants were showing up checked off correctly.  I just assumed there was something wrong with those.   Thanks so much for the tool!

**Comment by joshhunt** [comment]
I think this is fine now.
