### ISSUE TITLE
Suggestion: Allow us to manually manage data for dismantled items

### ISSUE THREAD

**Issue by JTF195** [joshhunt/destinySets#77]
It would be nice if we could manually flag and unflag items as dismantled

There are several items that are no longer available that I made the mistake of dismantling, and I also have several flagged that I definitely never obtained (Borealis, for example, when it isn't even available on PC)

**Comment by joshhunt** [comment]
Interesting - are you saying that Borealis is marked as obtained for you even though you’ve only ever played on PC?
  

  
Manually marking items is definitely something I want to add.   
  

  
  

  
  
>

**Comment by JTF195** [comment]
Yeah, Borealis, Legend of Acrius, several exotic armors, a bunch of emblems and a few emotes are marked as dismantled, because it is now correctly detecting that I don't have them in my vault kiosk.

**Comment by joshhunt** [comment]
Hmmm... Interesting. I was never aware I had this issue in the first place.

Ill look at sorting this out eventually.

**Comment by TheWolfLegate** [comment]
Has there been any progress on this? This feature would be greatly appreciated

**Comment by joshhunt** [comment]
pssst. I just released this one with a bit of a 'soft launch'. It's a bit hidden at the moment as I make sure everything works properly, but once connecting Google Drive, you can click on an item and a new button will appear in the modal 🎉 

Lemme know how it goes and what you think 😄
