### ISSUE TITLE
Mentors of Light incorrectly showing as collected

### ISSUE THREAD

**Issue by TheWolfLegate** [joshhunt/destinySets#80]
Is the all seasons tab supposed to only display Iron Banner, Raid, and Trials gear? Also, it is being displayed that I have the 'Mentor of Light' emblem when I do not

![destiny sets emblem error](https://user-images.githubusercontent.com/38706966/39219024-adb2a724-47ed-11e8-8e6b-158af56eb8c1.png)
![destiny 2 4_24_2018 6_10_04 pm](https://user-images.githubusercontent.com/38706966/39219031-b3ce2d9a-47ed-11e8-954a-b47a1f11ee74.png)

**Comment by joshhunt** [comment]
Yup - the All Seasons tab is a bit of an 'experiment' for how the site can show complete collections across multiple seasons. Expect it to grow further with time 😃 

That Mentors of Light emblem is interesting - I'm seeing the same thing yet I doubt I actually have it as well. I'll look into that - thanks for the heads up

**Comment by joshhunt** [comment]
Turns out I wasn't checking that your kiosk items were actually unlocked

> If true, the user can not only see the item, but they can acquire it. It is possible that a user can see a kiosk item and not be able to acquire it.

This should be fixed now via https://github.com/joshhunt/destinySets/commit/aa3cf93d2fdf100f6623ed45dfed0be9ae4e55a4

Thanks for reporting @TheWolfLegate  - the screenshot from in game was _very_ helpful!
