### ISSUE TITLE
Emblems that are no longer in the game

### ISSUE THREAD

**Issue by TheWolfLegate** [joshhunt/destinySets#81]
So the rare quality lost sector emblems (Lost Sector of Earth/Io/Nessus/Titan and Mercury Treasure seeker) no longer exist in the game. They were replaced with the legendary destination emblems. Is there anyway we can have them removed from the All Items page?

**Comment by joshhunt** [comment]
👍 Sounds fair.

This has been on the list of something for me to look into for a while.

**Comment by joshhunt** [comment]
For my reference: emblems in question are 2769834047, 3334815691, 3754910498, 4059318875, 4114707355

**Comment by TheWolfLegate** [comment]
Sweet, thanks for all the hard work you put into this

**Comment by TheWolfLegate** [comment]
There are a number of things in the all items tab that aren't/have never been acquirable. Removing them, while low priority would de-clutter that screen and be a QoL update. I feel like they could always be added back in later. Their hash numbers are: 

Shaders: (These are all generically applied to weapons when you receive them)

Dead Zone Bark (Worn) - 3921006356
Dead Zone Foliage (Worn) - 3921006353
Crucible Aspirant - 3450065543
Crucible Entrant (Worn) - 3450065541
Crucible Entrant - 3450065540
Crucible Aspirant (Worn) - 3450065536
Nessus Mirage (Worn) - 3403116797
Nessus Pursuit (Worn) - 3403116792
Desert Matte (Worn) - 2657932157
Powder Blue (Worn) - 2657932152
Echoes of Io (Worn) - 1489178152
Flowers of Io (Worn) - 1489178157
New Pacific Rush (Worn) - 1051938198
New Pacific Sink (Worn) - 1051938195

Emblems:

Rune of the Disciple - 776529032 (Lacking Display properties that imply it is broken)
Rune of the Adept - 776529033 (Lacking Display properties that imply it is broken)
Rune of the Oracle - 776529034 (Lacking Display properties that imply it is broken)
Aspect of Shadow - 855333069 (Lacking Display properties that imply it is broken)
Aspect of Dust - 855333070 (Lacking Display properties that imply it is broken)
Aspect of Blood - 855333071 (Lacking Display properties that imply it is broken)
Veteran Crest - 1723894000 (Lacking Display properties that imply it is broken)
Officer Crest - 1723894001 (Lacking Display properties that imply it is broken)
Commander Crest - 1723894003 (Lacking Display properties that imply it is broken)
Kadi 55-30's Blessing - 1940590818 (Unknown if obtainable at a later date or not)
In the Fire 1940590819 - (Unknown if obtainable at a later date or not)
Hellspawn 4182480235 - (Unknown if obtainable at a later date or not)
Silicon Frontier 4182480237 - (potentially could become obtainable with DLC2)
Order of Assassins 4212410112 - (Lacking Display properties that imply it is broken)
Heart of the City 4132147353 - (Unknown if obtainable at a later date or not)
Wish-Granter 4182480238 - (Unknown if obtainable at a later date or not)
Covetous Emperor 4261480750 - (Likely the Prestige Lair 1 emblem)

**Comment by andyschaefer** [comment]
Hellspawn is associated with the McFarlane figures being released later
this week (4/28).

**Comment by TheWolfLegate** [comment]
Okay, didn't know that, thanks. I think the rest is all correct though

**Comment by JTF195** [comment]
The worn shader variants aren't acquirable as an item drop, but they can be found on pre-shaded gear and should be able to be detected the same way ornaments are detected

For that matter, it would be nice if shaders could be considered 'owned' if the player has any gear with that shader equipped.

**Comment by joshhunt** [comment]
I've just blacklisted 2769834047, 3334815691, 3754910498, 4059318875 and 4114707355, as well as added some heuristics to remove a few more junk items.

The data files the site uses are aggressively cached in the browser, so you might not see these changes until a bit later :)
