### ISSUE TITLE
PS4 exclusives listed when using an xbox account

### ISSUE THREAD

**Issue by pfp-az** [joshhunt/destinySets#9]
I know for sure that the exotic Borealis is a PS4 exclusive but it shows up for me as an xbox user.
I would not bring this up except that I believe there are full armor sets exclusive to PS4 which are not shown so I'm assuming you are already filtering those out for xbox.

**Comment by joshhunt** [comment]
You don't see the PS4 exclusive armour sets because I they're just not there yet. This is now fixed and you should see all the PS4 gear ;)

But you're right, PS4 gear should be filtered out for Xbox accounts. I'll keep this open to track this.

**Comment by pfp-az** [comment]
If you are going to offer the ability to filter these it should be done in a way that can account for new exclusives as well as items coming off the exclusive list.

**Comment by joshhunt** [comment]
Fixed - there's now a filter to exclude PS4 items.
