### ISSUE TITLE
Warmind Items 

### ISSUE THREAD

**Issue by TheWolfLegate** [joshhunt/destinySets#90]
Warmind Items aren't showing up on the All Items tab for me
![destiny sets bug](https://user-images.githubusercontent.com/38706966/39793134-b1077f36-5309-11e8-909a-88cfa6fa625a.png)

**Comment by joshhunt** [comment]
Are they showing up now? I had some problems with my script to 'deploy' the new content update

**Comment by TheWolfLegate** [comment]
Negative. The warming tab is there but is just a blank page

**Comment by TheWolfLegate** [comment]
Got them now
