### ISSUE TITLE
Can’t figure out how to login

### ISSUE THREAD

**Issue by Evansblue787** [joshhunt/destinySets#95]
The website just shows every item but nothing I’ve collected. My gamer tag isn’t in the top right or anything. When the website asks me to authorize I go through the motions but nothing happens.

**Comment by joshhunt** [comment]
Hmm. Can you go to destinysets.com/debug and tell me if it reports an error? And pass on your debug ID?

**Comment by joshhunt** [comment]
Actually, thinking about this more, have you had problems since Warmind launched? Does DIM or the companion app work properly for you? There's an ongoing issue on Bungie's side. See https://twitter.com/BungieHelp/status/994643009214955521

The long and short of it is "Until resolved, players may workaround the issue by signing into all characters, on all platforms."

**Comment by Evansblue787** [comment]
Yeah I did that and the app worked for me as did Ishtar. But not destinysets. My debug id is 3qpwke7 and the error I’m getting through the debug says:

status: error, Bungie API Error DestinyUnexpectedError - An unexpected error has occurred on Bungie's servers while trying to grab Destiny information. URL: https://www.bungie.net/Platform/Destiny2/_/Profile/_/?components=100,101,102,103,200,201,202,203,204,205,300,301,302,303,304,305,306,307,308,400,401,402,500

**Comment by joshhunt** [comment]
Yeah, that’s the error from this ongoing issue. Is your bungie account linked to other platforms? I’m pretty sure that my site does not handle if one platform fails but the others succeed.   
  

  
  

  
  
>

**Comment by Evansblue787** [comment]
Ok so I went and logged in on all 9 of characters across all 3 platforms. Now I’m getting this:

Debug id is 9c6bc0d

Auth

isAuthenticated: true
authLoaded: true
Profile

status: error, The quota has been exceeded.
Defs

vendors: Loaded, 173 items
stats: Loaded, 44 items
items: Loaded, 5208 items
objectives: Loaded, 2076 items
Google Drive inventory revisions

**Comment by Evansblue787** [comment]
So yeah it looks like the error I’m getting is the quota has been exceeded. =(

**Comment by joshhunt** [comment]
Hmm well, there’s nothing with a quota that should cause problems, but maybe the quota error is masking something else.   
  

  
Can you clear your browser cache and try logging in on the main page again? Any errors in the JS console (F12)?
  

  
>

**Comment by Evansblue787** [comment]
Ugh I’ve been refreshing this page all day hoping for some kind of fix. I want to use this site so bad but for whatever reason I can’t. Feelsbadman

**Comment by joshhunt** [comment]
Try hitting "Clear all local DestinySets data" at https://destinysets.com/debug, or follow this https://support.apple.com/en-us/HT201265 to "Delete history, cache, and cookies"

**Comment by Evansblue787** [comment]
Still no luck. I’ll just use the site on pc I suppose. Thank you so much for helping me.

**Comment by Evansblue787** [comment]
Ok for some reason it works in private browsing on safari but not regular browsing?

**Comment by Evansblue787** [comment]
If you can still help me my debug ID is fz5fxak

It literally works everywhere except my iPhone. And on my iPhone it works in private browsing but that’s it. Still giving the error of quota has been exceeded.

**Comment by joshhunt** [comment]
Hey so I did some research into this and that error is reported by Safari when some of the internal browser storage that we use (specifically, localStorage and possibly IndexedDB) is full or not available. Now, the site has its own safeguards in place for that to mitigate errors, but it looks like something is somehow slipping through. Without more detail error reporting, it'll be hard to see what and fix it.

Reporting that it works in Private Browsing is interesting though - that would be the one place where i would expect it _not_ to work.

Can you confirm that you've ran through the steps at https://support.apple.com/en-us/HT201265 to delete history, cache, and cookies? That would be a good place to start from.

Also, can you confirm that you have enough free space on your iPhone? While the site doesn't store that much (my estimates put it at around 2mb), if your iPhone is running low on storage it might restrict what we can save as well.

**Comment by Evansblue787** [comment]
So I made sure I followed the steps in that help guide and I even reset my settings to factory settings. That still didn’t work. I also have only used about 25 gb out of 256 gb. So definitely not a space issue. I’m considering just resetting my phone to factory completely and seeing if that works.

**Comment by joshhunt** [comment]
Hmm okay.   
  

  
Doing a complete reset of your phone is up to you, but not something I would recommend right now.   
  

  
Give me a day or two and I’ll see if I can put together some better reporting to see exactly where this error is coming from.   
  

  
>

**Comment by Evansblue787** [comment]
Ok sounds good. Thank you so much

**Comment by killi2** [comment]
in debug I get "Profile - status: error, Failed to execute 'setItem' on 'Storage': Setting the value of 'd2Profile' exceeded the quota.

that is on PC, two different browsers.  Works fine on Android phone.

**Comment by joshhunt** [comment]
@Evansblue787 I've deployed some changes that should hopefully help mitigate some of the issues you've been facing. Note that things might take a bit longer to load or display (appears to be a problem with how I cache your inventory between visits), but it should at least display your inventory now :)

**Comment by Evansblue787** [comment]
Yes! It is working now. Thank you so much for all the help and sticking with me!
